apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
spec:
  selector:
    matchLabels:
      app: url-shortner
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
        - name: url-shortner
          image: noeltom/url-shortner:latest
          ports:
            - containerPort: 3000
        - name: db
          image: noeltom/db:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortner
spec:
  selector:
    app: url-shortner
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort